#!/bin/bash

# Check if all four parameters are provided
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Extract parameters
file_to_transfer="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_to_transfer" "$username@$server_ip":~/
else
    scp -o StrictHostKeyChecking=no "$file_to_transfer" "$username@$server_ip":~/
fi;
