#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# display FizzBuzz or Fizz or Buzz base on the number

for i in {1..100}
do
	if [[ $((i % 3)) -eq 0 && $((i % 5)) -eq 0 ]]
	then
		echo "FizzBuzz";

	elif [[ $((i % 3)) -eq 0 && $((i % 5)) -ne 0 ]]
	then
		echo "Fizz";

	elif [[ $((i % 5)) -eq 0 && $((i % 3)) -ne 0 ]]
	then
		echo "Buzz";
	else
		echo "$i";
	fi
done
