#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line.
content="Best School"
i=0;

while [[ $i -lt 10 ]]
do
	echo "$content";
	if [ $i = 8 ]
	then
		echo "Hi";
	fi
	(( i = i + 1 ))
done
