#!/usr/bin/env bash

# Connects to server 54.161.238.31  with key in ~/.ssh/school

#ssh -i ~/.ssh/school ubuntu@54.161.238.31

# Set the server address
server_address=54.161.238.31

# Set the private key file
private_key="~/.ssh/school"

# Use ssh with single-character flags to connect
ssh -i "$private_key" "ubuntu@$server_address"

